# tests/modules/test_audio_mixer.py
import pytest
from unittest.mock import MagicMock, patch
from config import VOICE_MAP

# Some presets (e.g. preset-8) generate native audio and carry no voice map at
# all. The voice-selection tests are meaningless there.
requires_voice_map = pytest.mark.skipif(
    not VOICE_MAP, reason="active preset has no voice_map (native-audio preset)"
)


@requires_voice_map
@patch("modules.audio_mixer.httpx")
def test_voiceover_uses_mapped_voice_for_known_genre(mock_httpx, monkeypatch, tmp_path):
    monkeypatch.setenv("ELEVENLABS_API_KEY", "el-key")

    mock_resp = MagicMock()
    mock_resp.status_code = 200  # _generate_voiceover raises on >= 400
    mock_resp.content = b"fake_mp3_bytes"
    mock_httpx.post.return_value = mock_resp

    genre, expected_voice_id = next(iter(VOICE_MAP.items()))

    from modules.audio_mixer import AudioMixer
    mixer = AudioMixer()
    mixer._generate_voiceover("In the void between stars...", genre, str(tmp_path))

    call_url = mock_httpx.post.call_args[0][0]
    assert expected_voice_id in call_url


@requires_voice_map
@patch("modules.audio_mixer.httpx")
def test_voiceover_falls_back_to_default_voice_for_unknown_genre(
    mock_httpx, monkeypatch, tmp_path
):
    monkeypatch.setenv("ELEVENLABS_API_KEY", "el-key")

    mock_resp = MagicMock()
    mock_resp.status_code = 200  # _generate_voiceover raises on >= 400
    mock_resp.content = b"fake_mp3_bytes"
    mock_httpx.post.return_value = mock_resp

    from modules.audio_mixer import AudioMixer
    mixer = AudioMixer()
    mixer._generate_voiceover("Something dark lurks...", "not-a-real-genre", str(tmp_path))

    # Unknown genres fall back to the first voice in the active preset's map
    call_url = mock_httpx.post.call_args[0][0]
    assert list(VOICE_MAP.values())[0] in call_url


@patch("modules.audio_mixer.subprocess.run")
@patch("modules.audio_mixer.AudioMixer._generate_bgm")
@patch("modules.audio_mixer.AudioMixer._generate_voiceover")
def test_mix_passes_video_voiceover_and_bgm_to_ffmpeg(
    mock_voiceover, mock_bgm, mock_run, monkeypatch, tmp_path
):
    monkeypatch.setenv("ELEVENLABS_API_KEY", "el-key")
    mock_voiceover.return_value = str(tmp_path / "voiceover.mp3")
    # BGM is generated by ElevenLabs Video-to-Music, not looked up from a static map
    mock_bgm.return_value = str(tmp_path / "bgm.mp3")

    from modules.audio_mixer import AudioMixer
    mixer = AudioMixer()
    video_path = str(tmp_path / "stitched.mp4")
    mixer.mix(video_path, "narrative text", "sci-fi")

    args = mock_run.call_args[0][0]
    assert args[0] == "ffmpeg"
    assert video_path in args
    assert str(tmp_path / "voiceover.mp3") in args
    assert str(tmp_path / "bgm.mp3") in args


@patch("modules.audio_mixer.subprocess.run")
@patch("modules.audio_mixer.AudioMixer._generate_bgm")
@patch("modules.audio_mixer.AudioMixer._generate_voiceover")
def test_mix_falls_back_to_voiceover_only_when_bgm_unavailable(
    mock_voiceover, mock_bgm, mock_run, monkeypatch, tmp_path
):
    monkeypatch.setenv("ELEVENLABS_API_KEY", "el-key")
    mock_voiceover.return_value = str(tmp_path / "voiceover.mp3")
    mock_bgm.return_value = None  # Video-to-Music failed; mix must still succeed

    from modules.audio_mixer import AudioMixer
    mixer = AudioMixer()
    mixer.mix(str(tmp_path / "stitched.mp4"), "narrative text", "sci-fi")

    args = mock_run.call_args[0][0]
    assert args[0] == "ffmpeg"
    assert str(tmp_path / "voiceover.mp3") in args
    assert "-filter_complex" not in args  # no amix stage without a BGM track


@patch("modules.audio_mixer.subprocess.run")
@patch("modules.audio_mixer.AudioMixer._generate_bgm")
@patch("modules.audio_mixer.AudioMixer._generate_voiceover")
def test_mix_output_path_is_final_mp4(
    mock_voiceover, mock_bgm, mock_run, monkeypatch, tmp_path
):
    monkeypatch.setenv("ELEVENLABS_API_KEY", "el-key")
    mock_voiceover.return_value = str(tmp_path / "voiceover.mp3")
    mock_bgm.return_value = None

    from modules.audio_mixer import AudioMixer
    mixer = AudioMixer()
    video_path = str(tmp_path / "stitched.mp4")
    output = mixer.mix(video_path, "narrative", "sci-fi")

    assert output == str(tmp_path / "final.mp4")


def test_mix_raises_on_non_stitched_path(monkeypatch, tmp_path):
    monkeypatch.setenv("ELEVENLABS_API_KEY", "el-key")

    from modules.audio_mixer import AudioMixer
    mixer = AudioMixer()

    with pytest.raises(ValueError, match="stitched.mp4"):
        mixer.mix(str(tmp_path / "wrong_name.mp4"), "narrative", "sci-fi")
