"""Per-shot Storyboard frames.

A Reference Image fixes *who* a character is. A Storyboard fixes *who, where and
in what pose* — one still per shot, generated by GPT Image 2 Edit with the
Reference Image as the base and the Shot Prompt as the instruction. Each becomes
that shot's first frame, which is what stops every shot opening on the same
static pose (the "wallpaper effect") while keeping the character identical.

Two prompt modes, chosen per shot:

  character present  the default. Preserve the main character's face, hair and
                     outfit from the Reference Image; let supporting characters
                     named in the Shot Prompt into the frame.

  character absent   POV, extreme-wide and exterior shots, where the Shot Prompt
                     says the main character is not visible. The Reference Image
                     is then a *style* anchor only — palette, world, art style.

Mode is detected from markers the script generator already writes for those shot
types (they come from the video-prompt-builder skill).

This module exists because the logic used to live in two places — orchestrator.py
and scripts/manual_episode.py — under a comment reading "keep this in sync with
orchestrator.py". They had already drifted: one interpolated the preset's video
style, the other hardcoded the word "illustration".
"""

from __future__ import annotations

from typing import Callable, Protocol

from modules.frame_chain import (
    FrameExtractionError,
    extract_last_frame,
    portrait_anchor,
    to_data_uri,
)


class ImageEditor(Protocol):
    """The one thing a storyboard generator needs: edit a base image."""

    def edit_image(self, base_image_url: str | list[str], prompt: str) -> str:
        ...


# Phrases the script generator writes when the main character is deliberately
# out of frame. Kept as data so it can be tested and extended without touching
# the prompt-building logic.
CHARACTER_ABSENT_MARKERS = (
    "pov shot", "pov push", "pov dolly",
    "extreme wide", "ews ", "ews,", "ews.",
    "from outside the ship", "outside the ship",
    "no character", "character is not visible", "character not visible",
    "camera pushes through", "camera dollies forward into",
    "the world widening", "the ship growing smaller",
)


def character_is_absent(shot_prompt: str) -> bool:
    """True when the Shot Prompt says the main character is not in frame."""
    lowered = shot_prompt.lower()
    return any(marker in lowered for marker in CHARACTER_ABSENT_MARKERS)


def build_edit_prompt(shot_prompt: str, style: str) -> str:
    """The instruction handed to GPT Image 2 Edit for one shot."""
    if character_is_absent(shot_prompt):
        return (
            f"Use the reference image as a STYLE anchor only — preserve the {style} "
            f"illustration style, color palette, and the world established in the reference. "
            f"The main character should NOT be in frame for this shot (it is a POV, "
            f"wide-exterior, or environmental shot). Render the scene exactly as the shot "
            f"prompt describes, as a 9:16 vertical still frame at the START of the action, "
            f"no motion blur. Scene: {shot_prompt}"
        )
    return (
        f"Use the reference image as the base — preserve the main character's face, "
        f"hair, outfit, and {style} style exactly. Render this scene as a 9:16 "
        f"vertical still frame at the START of the action, no motion blur. If the shot "
        f"prompt explicitly names other characters or entities (a holographic AI "
        f"manifesting as light, another person, a creature), include them rendered "
        f"exactly as the shot prompt describes. Scene: {shot_prompt}"
    )


def build_storyboards(
    shots: list[str],
    reference_image_url: str,
    *,
    style: str,
    generator: ImageEditor | None = None,
    log: Callable[[str], None] | None = None,
) -> list[str | None]:
    """Generate one Storyboard per shot.

    Returns a list the same length as `shots`. An entry is None when that shot's
    Storyboard could not be generated — the video producer falls back to the
    shared Reference Image for those, so one failure costs pose variety for a
    single shot rather than the whole episode.
    """
    if generator is None:
        from modules.image_generator import AtlasImageGenerator
        generator = AtlasImageGenerator()
    emit = log or (lambda message: print(message, flush=True))

    emit(f"[Storyboard] Generating {len(shots)} per-shot storyboards...")
    storyboards: list[str | None] = []
    for i, shot_prompt in enumerate(shots, start=1):
        prompt = build_edit_prompt(shot_prompt, style)
        try:
            storyboards.append(generator.edit_image(reference_image_url, prompt))
            emit(f"[Storyboard]   shot {i}/{len(shots)} ✓")
        except Exception as exc:
            emit(
                f"[Storyboard]   shot {i}/{len(shots)} FAILED ({exc}) "
                f"— falling back to the locked reference"
            )
            storyboards.append(None)
    return storyboards


def build_continuity_prompt(shot_prompt: str, style: str) -> str:
    """The instruction for a two-base edit.

    Probing showed the model resolves conflicts toward the TEXT, so precedence
    between the two images has to be stated rather than implied.
    """
    if character_is_absent(shot_prompt):
        return (
            f"You are given two images. The FIRST is a STYLE anchor — preserve the "
            f"{style} illustration style, colour palette and world from it. The SECOND "
            f"is the final moment of the previous shot — match its lighting, weather "
            f"and time of day so the two shots feel continuous. The main character "
            f"should NOT be in frame for this shot (it is a POV, wide-exterior, or "
            f"environmental shot). Render the scene as a 9:16 vertical still frame at "
            f"the START of the action, no motion blur. Scene: {shot_prompt}"
        )
    return (
        f"You are given two images. The FIRST image is the authority on WHO the "
        f"character is — preserve their face, hair, eye colour, outfit and the {style} "
        f"style from it exactly. The SECOND image is the final moment of the previous "
        f"shot — use it for continuity of lighting, weather, wardrobe state and where "
        f"other characters are standing, and keep any second character looking exactly "
        f"as they do there. Where the two images disagree about the main character's "
        f"appearance, the FIRST image wins. Render this scene as a 9:16 vertical still "
        f"frame at the START of the action, no motion blur. Scene: {shot_prompt}"
    )


class ChainedStoryboards:
    """A StoryboardSupplier that carries the previous shot's last frame forward.

    Shot 1 is edited from the Reference Image alone. Every shot after it is
    edited from [Reference Image, previous shot's last frame] -- so identity is
    re-anchored to the reference on every shot rather than drifting forward,
    while continuity still flows from what actually rendered.

    Extraction lives here rather than in the video producer so the producer
    never learns about ffmpeg or data URIs: it hands over a clip path and gets
    back a first frame.
    """

    def __init__(
        self,
        reference_image_url: str,
        *,
        style: str,
        generator: ImageEditor | None = None,
        log: Callable[[str], None] | None = None,
    ):
        if generator is None:
            from modules.image_generator import AtlasImageGenerator
            generator = AtlasImageGenerator()
        self._reference = reference_image_url
        self._style = style
        self._generator = generator
        self._log = log or (lambda message: print(message, flush=True))

    def frame_for(
        self, index: int, shot_prompt: str, previous_clip: str | None
    ) -> str | None:
        """The first-frame still for one shot, or None to fall back."""
        bases: str | list[str] = self._reference
        prompt = build_edit_prompt(shot_prompt, self._style)

        if previous_clip:
            try:
                frame = extract_last_frame(previous_clip)
                bases = [self._reference, to_data_uri(frame)]
                prompt = build_continuity_prompt(shot_prompt, self._style)
                self._log(f"[Storyboard]   shot {index + 1} chained to the previous frame")
            # Broad on purpose: extract_last_frame raises FrameExtractionError,
            # but to_data_uri shells out to ffmpeg with check=True, and
            # CalledProcessError is NOT an OSError. Anything that goes wrong
            # here costs continuity for one shot, never the episode.
            except Exception as exc:
                self._log(
                    f"[Storyboard]   shot {index + 1} could not chain ({exc}) "
                    f"— using the locked reference alone"
                )

        try:
            url = self._generator.edit_image(bases, prompt)
        except Exception as exc:
            self._log(
                f"[Storyboard]   shot {index + 1} FAILED ({exc}) "
                f"— falling back to the locked reference"
            )
            return None

        # Measured, not trusted: a two-base edit silently returns landscape.
        anchor = portrait_anchor(url)
        self._log(f"[Storyboard]   shot {index + 1} ✓")
        return anchor
