"""Per-shot Storyboard frames.

A Reference Image fixes *who* a character is. A Storyboard fixes *who, where and
in what pose* — one still per shot, generated by GPT Image 2 Edit with the
Reference Image as the base and the Shot Prompt as the instruction. Each becomes
that shot's first frame, which is what stops every shot opening on the same
static pose (the "wallpaper effect") while keeping the character identical.

Two prompt modes, chosen per shot:

  character present  the default. Preserve the main character's face, hair and
                     outfit from the Reference Image; let supporting characters
                     named in the Shot Prompt into the frame.

  character absent   POV, extreme-wide and exterior shots, where the Shot Prompt
                     says the main character is not visible. The Reference Image
                     is then a *style* anchor only — palette, world, art style.

Mode is detected from markers the script generator already writes for those shot
types (they come from the video-prompt-builder skill).

This module exists because the logic used to live in two places — orchestrator.py
and scripts/manual_episode.py — under a comment reading "keep this in sync with
orchestrator.py". They had already drifted: one interpolated the preset's video
style, the other hardcoded the word "illustration".
"""

from __future__ import annotations

from typing import Callable, Protocol


class ImageEditor(Protocol):
    """The one thing a storyboard generator needs: edit a base image."""

    def edit_image(self, base_image_url: str, prompt: str) -> str:
        ...


# Phrases the script generator writes when the main character is deliberately
# out of frame. Kept as data so it can be tested and extended without touching
# the prompt-building logic.
CHARACTER_ABSENT_MARKERS = (
    "pov shot", "pov push", "pov dolly",
    "extreme wide", "ews ", "ews,", "ews.",
    "from outside the ship", "outside the ship",
    "no character", "character is not visible", "character not visible",
    "camera pushes through", "camera dollies forward into",
    "the world widening", "the ship growing smaller",
)


def character_is_absent(shot_prompt: str) -> bool:
    """True when the Shot Prompt says the main character is not in frame."""
    lowered = shot_prompt.lower()
    return any(marker in lowered for marker in CHARACTER_ABSENT_MARKERS)


def build_edit_prompt(shot_prompt: str, style: str) -> str:
    """The instruction handed to GPT Image 2 Edit for one shot."""
    if character_is_absent(shot_prompt):
        return (
            f"Use the reference image as a STYLE anchor only — preserve the {style} "
            f"illustration style, color palette, and the world established in the reference. "
            f"The main character should NOT be in frame for this shot (it is a POV, "
            f"wide-exterior, or environmental shot). Render the scene exactly as the shot "
            f"prompt describes, as a 9:16 vertical still frame at the START of the action, "
            f"no motion blur. Scene: {shot_prompt}"
        )
    return (
        f"Use the reference image as the base — preserve the main character's face, "
        f"hair, outfit, and {style} style exactly. Render this scene as a 9:16 "
        f"vertical still frame at the START of the action, no motion blur. If the shot "
        f"prompt explicitly names other characters or entities (a holographic AI "
        f"manifesting as light, another person, a creature), include them rendered "
        f"exactly as the shot prompt describes. Scene: {shot_prompt}"
    )


def build_storyboards(
    shots: list[str],
    reference_image_url: str,
    *,
    style: str,
    generator: ImageEditor | None = None,
    log: Callable[[str], None] | None = None,
) -> list[str | None]:
    """Generate one Storyboard per shot.

    Returns a list the same length as `shots`. An entry is None when that shot's
    Storyboard could not be generated — the video producer falls back to the
    shared Reference Image for those, so one failure costs pose variety for a
    single shot rather than the whole episode.
    """
    if generator is None:
        from modules.image_generator import AtlasImageGenerator
        generator = AtlasImageGenerator()
    emit = log or (lambda message: print(message, flush=True))

    emit(f"[Storyboard] Generating {len(shots)} per-shot storyboards...")
    storyboards: list[str | None] = []
    for i, shot_prompt in enumerate(shots, start=1):
        prompt = build_edit_prompt(shot_prompt, style)
        try:
            storyboards.append(generator.edit_image(reference_image_url, prompt))
            emit(f"[Storyboard]   shot {i}/{len(shots)} ✓")
        except Exception as exc:
            emit(
                f"[Storyboard]   shot {i}/{len(shots)} FAILED ({exc}) "
                f"— falling back to the locked reference"
            )
            storyboards.append(None)
    return storyboards
