"""Export the populated characters sheet to a markdown file for offline reference.

The sheet is the source of truth at runtime. This file is a static snapshot
for human reading — useful when the sheet is offline, when reviewing the
canon, or when designing reference images.
"""
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from dotenv import load_dotenv

load_dotenv(PROJECT_ROOT / ".env")

from modules.characters_reader import CharactersReader

records = CharactersReader().get_all_characters()
if not records:
    raise SystemExit(
        "No characters found. Check ALAN_STORY_CHARACTERS_GOOGLE_SHEET_ID is set "
        "and the sheet is shared with the service account."
    )

OUT = PROJECT_ROOT / "chronicle of zenith" / "chronicle-of-zenith-characters-locked.md"

ROLE_ICON = {"main": "Hero", "villain": "Villain", "ally": "Ally", "mentor": "Mentor", "mystery": "Mystery"}

lines = []
lines.append("# THE CHRONICLE OF ZENITH")
lines.append("")
lines.append("## Characters — Locked Roster")
lines.append("")
lines.append("This file is a **runtime snapshot** of `ALAN_STORY_CHARACTERS_GOOGLE_SHEET_ID`,")
lines.append("the Google Sheet read by `modules/characters_reader.py` on every preset-7 episode brief.")
lines.append("")
lines.append("**Source of truth = the sheet.** This file is regenerated by `scripts/export_characters.py`")
lines.append("any time the sheet is updated. Don't hand-edit this file — edit the sheet and re-export.")
lines.append("")
lines.append("Companion files:")
lines.append("")
lines.append("- `chronicle-of-zenith-series-bible.md` — locked canon (themes, mythology, arcs)")
lines.append("- `chronicle-of-zenith-character-roster.md` — original design-intent roster (with cut/keep recommendations)")
lines.append("- `chronicle-of-zenith-story-guide.md` — storytelling craft and macro architecture")
lines.append("- `chronicle-of-zenith-production-workflow.md` — Seedance + GPT Image 2 production pipeline")
lines.append("")

# Group characters by role
by_role = {"main": [], "ally": [], "mentor": [], "villain": [], "mystery": []}
for r in records:
    role = str(r.get("role", "")).strip().lower() or "ally"
    by_role.setdefault(role, []).append(r)

# Master cast list
lines.append("---")
lines.append("")
lines.append("## Master Cast List")
lines.append("")
lines.append("| Character | Alias | Role | Arcs Active | Status |")
lines.append("|-----------|-------|------|-------------|--------|")
for r in records:
    name = r.get("character_name", "")
    alias = r.get("alias", "") or "—"
    role = str(r.get("role", "")).strip()
    arcs = str(r.get("arcs_active", "")).strip() or "—"
    status = str(r.get("status", "")).strip() or "active"
    lines.append(f"| **{name}** | {alias} | {role} | {arcs} | {status} |")
lines.append("")
lines.append(f"**Total characters:** {len(records)}")
lines.append("")

# Detailed character entries
lines.append("---")
lines.append("")
lines.append("## Character Profiles")
lines.append("")

for r in records:
    name = r.get("character_name", "")
    alias = r.get("alias", "")
    role = str(r.get("role", "")).strip()
    relation = r.get("relation_to_main", "")
    appearance_n = r.get("appearance_normal", "")
    appearance_t = r.get("appearance_transformed", "")
    ref_n = r.get("ref_image_normal", "")
    ref_t = r.get("ref_image_transformed", "")
    backstory = r.get("backstory", "")
    first_ep = r.get("first_episode", "")
    arcs = r.get("arcs_active", "")
    status = r.get("status", "")

    title_line = f"### {name}"
    if alias:
        title_line += f" / *{alias}*"
    lines.append(title_line)
    lines.append("")

    # Quick reference table
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    lines.append(f"| Role | {role} |")
    lines.append(f"| Relation to main | {relation or '—'} |")
    lines.append(f"| First episode | {first_ep or '—'} |")
    lines.append(f"| Arcs active | {arcs or '—'} |")
    lines.append(f"| Status | {status or 'active'} |")
    if ref_n:
        lines.append(f"| Reference image (normal) | [link]({ref_n}) |")
    else:
        lines.append("| Reference image (normal) | _not yet generated_ |")
    if appearance_t:
        if ref_t:
            lines.append(f"| Reference image (transformed) | [link]({ref_t}) |")
        else:
            lines.append("| Reference image (transformed) | _not yet generated_ |")
    lines.append("")

    if backstory:
        lines.append("**Backstory:**")
        lines.append("")
        lines.append(f"> {backstory}")
        lines.append("")

    if appearance_n:
        lines.append("**LOCKED APPEARANCE (normal):**")
        lines.append("")
        lines.append(f"> {appearance_n}")
        lines.append("")

    if appearance_t:
        lines.append("**LOCKED APPEARANCE (transformed):**")
        lines.append("")
        lines.append(f"> {appearance_t}")
        lines.append("")

    lines.append("---")
    lines.append("")

# Per-arc index
lines.append("## Per-Arc Active Cast")
lines.append("")
lines.append("Computed from each character's `arcs_active` column. The brief generator")
lines.append("uses this exact filtering to inject the right roster per episode.")
lines.append("")
for arc_n in range(1, 11):
    active = [r for r in records if str(arc_n) in str(r.get("arcs_active", "")).split(",")]
    names = [r.get("character_name", "") for r in active]
    lines.append(f"### Arc {arc_n} ({len(names)} characters)")
    lines.append("")
    for n in names:
        lines.append(f"- {n}")
    lines.append("")

OUT.write_text("\n".join(lines))
print(f"Wrote {OUT}")
print(f"  {len(records)} characters")
print(f"  {OUT.stat().st_size:,} bytes")
